### ISSUE TITLE
Missing runtime dependencies: gcc and gmp-static

### ISSUE THREAD

**Issue by amazari** [fedora-haskell/stack#1]
Hi,
GHC requires both gcc and gmp-static at runtime. As those dependencies are not enforced, and when using a stack-installed GHC, this results in a unusable installation:

```
[scaroo@xipi ~] $ stack setup
Configuring GHCi with the following packages: 
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
ghc: could not execute: /usr/bin/gcc

[scaroo@xipi ~] $ sudo dnf install gcc
...
[scaroo@xipi ~] $ stack setup
The GHC located at /home/scaroo/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc failed to compile a sanity check. Please see:

    http://docs.haskellstack.org/en/stable/install_and_upgrade/

for more information. Exception was:
Running /home/scaroo/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc /tmp/stack-sanity-check3279/Main.hs -no-user-package-db in directory /tmp/stack-sanity-check3279/ exited with ExitFailure 1

[1 of 1] Compiling Main             ( /tmp/stack-sanity-check3279/Main.hs, /tmp/stack-sanity-check3279/Main.o )
Linking /tmp/stack-sanity-check3279/Main ...

/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status

[scaroo@xipi ~] $ sudo dnf install gmp-static
...
[scaroo@xipi ~] $ stack setup
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

```

AFAIK, there are 2 ways of solving this issue:
 - make this package depends on 'gcc' and 'gmp-static' packages
 - make this package depends on 'ghc' package. Stack would then default to system-wide ghc. Stack-installed GHC should also work, as the 2 deps would be transitively pulled.

Thanks for your time and work!

**Comment by juhp** [comment]
Oops I missed this: that is a good point, specially now that stack no longer uses system ghc by default.

**Comment by juhp** [comment]
Isn't `gmp-devel` sufficient? That is what Fedora ghc pulls in.

**Comment by juhp** [comment]
I am building https://copr.fedorainfracloud.org/coprs/petersen/stack/build/780703/

**Comment by juhp** [comment]
Rawhide will come in the next build after buildroot is fixed.
I am going to close this but please reopen if you still see issues.
And thanks for the report!
